name: tests
on: [push]
jobs:
  tox-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: python3 -m pip install tox
      - name: Run flake8
        run: tox -e flake8
      - name: Run pylint
        run: tox -e pylint
      - name: Run unit tests (py310)
        run: tox -e py310

